config/routes.rb
Rails.application.routes.draw do
  resources :forums do
    resources :topics do
      resources :posts
      resource :monitorship, :controller => :monitorships
    end
  end

  resources :posts, :as => "all_posts" do
    collection do
      get :index, :as => "all"
      get :search, :as => "search_all"
    end
  end

  %w(forum).each do |attr|
    resources :posts, :as => "#{attr}_posts", :path_prefix => "/#{attr.pluralize}/:#{attr}_id"
  end

  resources :topics
  resources :monitorship
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  acts_as_list

  validates_presence_of :name

  has_many :moderatorships, :dependent => :delete_all
  has_many :moderators, :through => :moderatorships, :source => :user

  has_many :topics, :order => 'sticky desc, replied_at desc', :dependent => :delete_all
  has_one  :recent_topic, :class_name => 'Topic', :order => 'sticky desc, replied_at desc'

  # this is used to see if a forum is "fresh"... we can't use topics because it puts
  # stickies first even if they are not the most recently modified
  has_many :recent_topics, :class_name => 'Topic', :order => 'replied_at DESC'
  has_one  :recent_topic,  :class_name => 'Topic', :order => 'replied_at DESC'

  has_many :posts,     :order => "#{Post.table_name}.created_at DESC", :dependent => :delete_all
  has_one  :recent_post, :order => "#{Post.table_name}.created_at DESC", :class_name => 'Post'

  format_attribute :description
  
  # retrieves forums ordered by position
  def self.find_ordered(options = {})
    find :all, options.update(:order => 'position')
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  
	before_filter :login_required
  before_filter :find_or_initialize_forum, :except => :index
	before_filter :admin?, :except => [:show, :index]

  cache_sweeper :posts_sweeper, :only => [:create, :update, :destroy]

  def index
    @forums = Forum.find_ordered
    # reset the page of each forum we have visited when we go back to index
    session[:forum_page] = nil
    respond_to do |format|
      format.html
      format.xml { render :xml => @forums }
    end
  end  

  def show
    respond_to do |format|
      format.html do
        # keep track of when we last viewed this forum for activity indicators
        (session[:forums] ||= {})[@forum.id] = Time.now.utc if logged_in?
        (session[:forum_page] ||= Hash.new(1))[@forum.id] = params[:page].to_i if params[:page]

        @topics = @forum.topics.paginate :page => params[:page]
        User.find(:all, :conditions => ['id IN (?)', @topics.collect { |t| t.replied_by }.uniq]) unless @topics.blank?
      end
      format.xml { render :xml => @forum }
    end
  end

  # new renders new.html.erb  
  def create
    @forum.attributes = params[:forum]
    @forum.save!
    respond_to do |format|
      format.html { redirect_to @forum }
      format.xml  { head :created, :location => forum_url(@forum, :format => :xml) }
    end
  end

  def update
    @forum.update_attributes!(params[:forum])
    respond_to do |format|
      format.html { redirect_to @forum }
      format.xml  { head 200 }
    end
  end
  
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_path }
      format.xml  { head 200 }
    end
  end
  
  protected
    def find_or_initialize_forum
      @forum = params[:id] ? Forum.find(params[:id]) : Forum.new
    end

  #alias authorized? admin?
  
end

app/helpers/forums_helper.rb
module ForumsHelper
  
  # used to know if a topic has changed since we read it last
  def recent_topic_activity(topic)
    return false if not logged_in?
    return topic.replied_at > ((session[:topics] && session[:topics][topic.id]) || 3.days.ago) # was: last_active.  TODO: Could implement something to look at the user
  end 
  
  # used to know if a forum has changed since we read it last
  def recent_forum_activity(forum)
		return false unless logged_in? && forum.recent_topic
    return forum.recent_topic.replied_at > ((session[:forums] && session[:forums][forum.id]) || 3.days.ago) # was: last_active.  TODO: Could implement something to look at the user
  end
  
end

app/views/forums/_form.html.erb
<p style="float:right; margin-top:0">
</p>

<p id="forum_name">

<table border="0" cellspacing="0" cellpadding="0" class="noborder nopad wide">
  <td>
    <label><%= 'Title'[:title_title] %></label><br />
    <%= form.text_field :name, :class => "primary" %>
  </td>
  <td style="text-align:right">
    <label><%= 'Position'[:position_title] %></label><br />
    <%= form.text_field :position, :size => 5 %>

  </td>
</table>

</p>
<p id="forum_descripion">
<label><%= 'Description'[:description_title] %></label><br />
<%= form.text_area :description, :rows => 7 %></p>

app/views/forums/edit.html.erb
<div class="crumbs">
  <%= link_to 'Forums'[:forums_title], forums_path %> <span class="arrow">&rarr;</span>
</div>

<h1><%= 'Edit Forum'[:edit_forum] %></h1>

<% form_for :forum,
     :url  => forum_path(@forum),
     :html => { :method => :put } do |f| -%>
<%= render :partial => "form", :object => f %>
<%= submit_tag 'Save Forum'[:save_forum] -%> or <%= link_to('Cancel'[:cancel], forums_path) %>
<% end -%>

app/views/forums/index.html.erb
<% content_for :right do %>

<% if admin? %>
<h6><%= 'Admin'[:admin_title] %></h6>
<p><%= link_to 'Create New Forum'[:create_new_forum], new_forum_path, :class => "utility" %></p>
<% end %>

<% end %>

<h1 style="margin-top:0;"><%= 'Forums'[:forums_title] %></h1>
<p class="subtitle">
<%= feed_icon_tag "Recent Posts"[:recent_posts], all_posts_path(:format => 'rss') %>
<%= '{count} topic(s)'[(count=Topic.count)==1 ? :topic_count : :topics_count, number_with_delimiter(count)] %>, 
<%= '{count} post(s)'[(count=Post.count)==1 ? :post_count : :posts_count, number_with_delimiter(count)] %>, <%= '{count} voice(s)'[(count=User.count(:conditions => "posts_count > 0"))==1 ? :voice_count : :voices_count, number_with_delimiter(count)] %>
  
</p>

<table border="0" cellspacing="0" cellpadding="0" class="wide forums">
  <tr>
    <th class="la" width="70%" colspan="3"><%= 'Forum'[:forum_title] %></th>
<!--
    <th width="5%">Topics</th>
    <th width="5%">Posts</th>
-->
    <th class="la" width="30%" colspan="1"><%= 'Last Post'[:last_post] %></th>
  </tr>
<% for forum in @forums do %>  
  <tr>
    <td class="vat c1">
    
      <% if recent_forum_activity(forum) %>
      <%= image_tag "savage_beast/clearbits/comment.gif", :class => "icon green", :title => 'Recent activity'[:recent_activity] %>
      <% else %>
      <%= image_tag "savage_beast/clearbits/comment.gif", :class => "icon grey", :title => 'No recent activity'[:no_recent_activity] %>
      <% end %>
    </td>
    <td class="c2 vat">
      <%= link_to h(forum.name), forum_path(forum), :class => "title" %>
      <div class="posts">
        <%= '{count} topics'[(count=forum.topics.size)==1 ? :topic_count : :topics_count, number_with_delimiter(count)] %>, 
        <%= '{count} posts'[(count=forum.posts.size)==1 ? :post_count : :posts_count, number_with_delimiter(count)] %>
      </div>
      <p class="desc"><%= forum.description_html %>
        </p>
    </td>
    <td class="c3">
      <%= link_to 'Edit'[:edit_title], edit_forum_path(forum), :class => "tiny", :rel => "directory", :style => "float:right" if admin? %>
    </td>

    <td class="inv lp">
      <% if forum.recent_post %>
        <%= time_ago_in_words(forum.recent_post.created_at) %><br />
        <%= 'by {user}'[:by_user,"<strong>#{h(forum.recent_post.user.display_name)}</strong>"] %>
        <span>(<%= link_to 'view'[], forum_topic_path(:forum_id => forum, :id => forum.recent_post.topic_id, :page => forum.recent_post.topic.last_page, :anchor => forum.recent_post.dom_id) %>)</span>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<p>
  <%= link_to 'Recent posts'[:recent_posts], all_posts_path %>
</p>

<% online_users = User.currently_online -%>
<% unless !online_users || online_users.empty? %>
<div class="stats">
<div class="users">
<% unless !online_users || online_users.empty? %>
<%= 'Users online:'[:users_online] %> <%= online_users.map { |u| link_to "<strong>#{h u.display_name}</strong>", user_path(u) } * ", " %><br />
<% end %>
</div>
</div>
<% end %>

app/views/forums/new.html.erb
<div class="crumbs">
	<%= link_to "Forums"[:forums_title], forums_path %> <span class="arrow">&rarr;</span>
</div>

<h1><%= 'New Forum'[:new_forum] %></h1>

<% form_for :forum, :url => forums_path do |f| -%>
<%= render :partial => "form", :object => f %>
<%= submit_tag 'Create'[:Create] -%> or <%= link_to('Cancel'[:cancel], forums_path) -%>
<% end -%>

app/views/forums/show.html.erb
<% content_for :right do %>

<% unless @forum.description.blank? %>
<%= @forum.description_html %>
<hr />
<% end %>

<h5 style="margin-bottom:1.0em;"><%= 'Moderators'[:moderators] %></h5>

<% unless @forum.moderators.empty? -%>
<ul class="flat" style="margin-top:1em;">
<% @forum.moderators.each do |user| -%>
  <li><%= link_to user.display_name, user_path(user) %></li>
<% end -%>
</ul>
<% else -%>
<p><%= 'This forum is currently unmoderated.'[:forum_is_unmoderated] %></p>
<p><%= 'Please always be courteous.'[:please_be_courteous] %></p>
<% end -%>

<% end %>

<% @page_title = @forum.name %>

<div class="crumbs">
<%= link_to 'Forums'[:forums_title], forums_path %> <span class="arrow">&rarr;</span>
</div>
<h1 style="margin-top:0.5em">
  <%= h @forum.name %>
</h1>

<p class="subtitle">
  <%= feed_icon_tag @forum.name, forum_posts_path(@forum, :format => :rss) %> 
  <%= '{count} topic(s)'[(count=@forum.topics.size)==1 ? :topic_count : :topics_count, number_with_delimiter(count)] %>, 
  <%= '{count} post(s)'[(count=@forum.posts.size)==1 ? :post_count : :posts_count, number_with_delimiter(count)] %>
</p>
	
<% if @topics.total_pages > 1 -%>
<% if logged_in? %>
<p style="float:right; margin-top:0;"><%= link_to 'New topic'[], new_forum_topic_path(@forum), :class => "utility" %></p>
<% end %>
<%= will_paginate @topics %>
<% end -%>

<table border="0" cellspacing="0" cellpadding="0" class="wide topics">
<tr>
  <th class="la" colspan="2"><%= 'Topic'[:topic_title] %></th>
  <th width="1%"><%= 'Posts'[:posts_title] %></th>
  <th width="1%"><%= 'Views'[:views_title] %></th>
  <th class="la"><%= 'Last post'[:last_post] %></th>
</tr>
<% for topic in @topics %>
<tr class="hentry">
  <td style="padding:5px; width:16px;" class="c1">
    <% 
    icon = "comment"
    color = ""
    if topic.locked?
      icon = "lock"
      post = ", this topic is locked."[:comma_locked_topic]
      color = "darkgrey"
    end
    %>
    <% if recent_topic_activity(topic) %>
    <%= image_tag "savage_beast/clearbits/#{icon}.gif", :class => "icon green", :title => "Recent activity"[]+"#{post}" %>
    <% else %>
      <%= image_tag "savage_beast/clearbits/#{icon}.gif", :class => "icon grey #{color}", :title => "No recent activity"[]+"#{post}" %>
    <% end %>
  </td>
  <td class="c2">
    <%= "Sticky"[:sticky_title]+": <strong>" if topic.sticky? %>
    <%= topic_title_link (topic), :class => "entry-title", :rel => "bookmark" %>
    <%#= link_to h(topic.title), topic_path(@forum, topic), :class => "entry-title", :rel => "bookmark" %>
    <%= "</strong>" if topic.sticky? %>
    <% if topic.paged? -%>
    <small><%= link_to 'last'[], forum_topic_path(:forum_id => @forum, :id => topic, :page => topic.last_page) %></small>
    <% end -%>
  </td>
  <td class="ca inv stat"><%= topic.posts.size %></td>
  <td class="ca inv stat"><%= number_with_delimiter(topic.views) %></td>
  <td class="lp">
    <abbr class="updated" title="<%= topic.replied_at.xmlschema %>"><%= time_ago_in_words(topic.replied_at) %></abbr>
    <%= 'by {user}'[:by_user, "<span class=\"author\"><strong class=\"fn\">#{h(topic.replied_by_user.display_name)}</strong></span>"] %>
    <span><%= link_to 'view'[], forum_topic_path(:forum_id => @forum, :id => topic, :page => topic.last_page, :anchor => "posts-#{topic.last_post_id}") %></span>
  </td>
</tr>
<% end %>
</table>

<%= will_paginate @topics %>

<% if logged_in? %>
<p><%= link_to 'New topic'[:new_topic], new_forum_topic_path(@forum), :class => "utility" %></p>
<% end%>