config/routes.rb
Rails.application.routes.draw do
  resources :forums do
    resources :topics do
      resources :posts
      resource :monitorship, :controller => :monitorships
    end
  end

  resources :posts, :as => "all_posts" do
    collection do
      get :index, :as => "all"
      get :search, :as => "search_all"
    end
  end

  %w(forum).each do |attr|
    resources :posts, :as => "#{attr}_posts", :path_prefix => "/#{attr.pluralize}/:#{attr}_id"
  end

  resources :topics
  resources :monitorship
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates_presence_of :forum, :user, :title
  before_create  :set_default_replied_at_and_sticky
  before_update  :check_for_changing_forums
  after_save     :update_forum_counter_cache
  before_destroy :update_post_user_counts
  after_destroy  :update_forum_counter_cache

  belongs_to :forum
  belongs_to :user
  belongs_to :last_post, :class_name => "Post", :foreign_key => 'last_post_id'
  has_many :monitorships
  has_many :monitors, :through => :monitorships, :conditions => ["#{Monitorship.table_name}.active = ?", true], :source => :user

  has_many :posts,     :order => "#{Post.table_name}.created_at", :dependent => :delete_all
  has_one  :recent_post, :order => "#{Post.table_name}.created_at DESC", :class_name => 'Post'
  
  has_many :voices, :through => :posts, :source => :user, :uniq => true
  belongs_to :replied_by_user, :foreign_key => "replied_by", :class_name => "User"

  attr_accessible :title
  # to help with the create form
  attr_accessor :body
	
	def hit!
    self.class.increment_counter :hits, id
  end

  def sticky?() sticky == 1 end

  def views() hits end

  def paged?() posts_count > Post.per_page end
  
  def last_page
    [(posts_count.to_f / Post.per_page).ceil.to_i, 1].max
  end

  def editable_by?(user)
    user && (user.id == user_id || user.admin? || user.moderator_of?(forum_id))
  end
  
  def update_cached_post_fields(post)
    # these fields are not accessible to mass assignment
    remaining_post = post.frozen? ? recent_post : post
    if remaining_post
      self.class.update_all(['replied_at = ?, replied_by = ?, last_post_id = ?, posts_count = ?', 
        remaining_post.created_at, remaining_post.user_id, remaining_post.id, posts.count], ['id = ?', id])
    else
      self.destroy
    end
  end
  
  protected
    def set_default_replied_at_and_sticky
      self.replied_at = Time.now.utc
      self.sticky   ||= 0
    end

    def set_post_forum_id
      Post.update_all ['forum_id = ?', forum_id], ['topic_id = ?', id]
    end

    def check_for_changing_forums
      old = Topic.find(id)
      @old_forum_id = old.forum_id if old.forum_id != forum_id
      true
    end
    
    # using count isn't ideal but it gives us correct caches each time
    def update_forum_counter_cache
      forum_conditions = ['topics_count = ?', Topic.count(:id, :conditions => {:forum_id => forum_id})]
      # if the topic moved forums
      if !frozen? && @old_forum_id && @old_forum_id != forum_id
        set_post_forum_id
        Forum.update_all ['topics_count = ?, posts_count = ?', 
          Topic.count(:id, :conditions => {:forum_id => @old_forum_id}),
          Post.count(:id,  :conditions => {:forum_id => @old_forum_id})], ['id = ?', @old_forum_id]
      end
      # if the topic moved forums or was deleted
      if frozen? || (@old_forum_id && @old_forum_id != forum_id)
        forum_conditions.first << ", posts_count = ?"
        forum_conditions       << Post.count(:id, :conditions => {:forum_id => forum_id})
      end
      # User doesn't have update_posts_count method in SB2, as reported by Ryan
			#@voices.each &:update_posts_count if @voices
      Forum.update_all forum_conditions, ['id = ?', forum_id]
      @old_forum_id = @voices = nil
    end
    
    def update_post_user_counts
      @voices = voices.to_a
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :find_forum_and_topic, :except => :index
  before_filter :login_required, :only => [:new, :create, :edit, :update, :destroy]

	# @WBH@ TODO: This uses the caches_formatted_page method.  In the main Beast project, this is implemented via a Config/Initializer file.  Not
	# sure what analogous place to put it in this plugin.  It don't work in the init.rb  
  #caches_formatted_page :rss, :show
  cache_sweeper :posts_sweeper, :only => [:create, :update, :destroy]

  def index
    respond_to do |format|
      format.html { redirect_to forum_path(params[:forum_id]) }
      format.xml do
        @topics = Topic.paginate_by_forum_id(params[:forum_id], :order => 'sticky desc, replied_at desc', :page => params[:page])
        render :xml => @topics.to_xml
      end
    end
  end

  def new
    @topic = Topic.new
  end
  
  def show
    respond_to do |format|
      format.html do
        # see notes in application.rb on how this works
        update_last_seen_at
        # keep track of when we last viewed this topic for activity indicators
        (session[:topics] ||= {})[@topic.id] = Time.now.utc if logged_in?
        # authors of topics don't get counted towards total hits
        @topic.hit! unless logged_in? and @topic.user == current_user
        @posts = @topic.posts.paginate :page => params[:page]
        User.find(:all, :conditions => ['id IN (?)', @posts.collect { |p| p.user_id }.uniq]) unless @posts.blank?
        @post   = Post.new
      end
      format.xml do
        render :xml => @topic.to_xml
      end
      format.rss do
        @posts = @topic.posts.find(:all, :order => 'created_at desc', :limit => 25)
        render :action => 'show', :layout => false
      end
    end
  end
  
  def create
    topic_saved, post_saved = false, false
		# this is icky - move the topic/first post workings into the topic model?
    Topic.transaction do
	    @topic  = @forum.topics.build(params[:topic])
      assign_protected
      @post       = @topic.posts.build(params[:topic])
      @post.topic = @topic
      @post.user  = current_user
      # only save topic if post is valid so in the view topic will be a new record if there was an error
      @topic.body = @post.body # incase save fails and we go back to the form
      topic_saved = @topic.save if @post.valid?
      post_saved = @post.save 
    end
		
		if topic_saved && post_saved
			respond_to do |format| 
				format.html { redirect_to forum_topic_path(@forum, @topic) }
				format.xml  { head :created, :location => topic_url(:forum_id => @forum, :id => @topic, :format => :xml) }
			end
		else
			render :action => "new"
		end
  end
  
  def update
    @topic.attributes = params[:topic]
    assign_protected
    @topic.save!
    respond_to do |format|
      format.html { redirect_to forum_topic_path(@forum, @topic) }
      format.xml  { head 200 }
    end
  end
  
  def destroy
    @topic.destroy
    flash[:notice] = "Topic '{title}' was deleted."[:topic_deleted_message, @topic.title]
    respond_to do |format|
      format.html { redirect_to forum_path(@forum) }
      format.xml  { head 200 }
    end
  end
  
  protected
    def assign_protected
      @topic.user     = current_user if @topic.new_record?
      # admins and moderators can sticky and lock topics
      return unless admin? or current_user.moderator_of?(@topic.forum)
      @topic.sticky, @topic.locked = params[:topic][:sticky], params[:topic][:locked] 
      # only admins can move
      return unless admin?
      @topic.forum_id = params[:topic][:forum_id] if params[:topic][:forum_id]
    end
    
    def find_forum_and_topic
      @forum = Forum.find(params[:forum_id])
      @topic = @forum.topics.find(params[:id]) if params[:id]
    end
    
    def authorized?
      %w(new create).include?(action_name) || @topic.editable_by?(current_user)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<p>
<label for="topic_title"><%= 'Title'[:title_title] %></label><br />
<%= form.text_field :title, :onchange => "/*TopicForm.editNewTitle(this);*/", :class => "primary", :tabindex => 10 %>

<% if admin? or current_user.moderator_of?(@topic.forum) %>
<label style="margin-left:1em;">
<%= form.check_box :sticky %> <%= 'Sticky'[:sticky_title] %>
</label>

<label style="margin-left:1em;">
<%= form.check_box :locked %> <%= 'Locked'[:locked_title] %>
</label>

<% end %>

</p>
<% if @topic.new_record? %>
<p>
<label for="topic_body"><%= 'Body'[:body_title] %></label><br />
<%= form.text_area :body, :rows => 12, :tabindex => 20 %></p>
<% end %>

<% if admin? and not @topic.new_record? %>
<p id="topic_forum_id">
  <label for="topic_forum_id"><%= 'Forum'[:forum_title] %></label><br />
  <%= form.select :forum_id, Forum.find(:all, :order => "position").map {|x| [x.name, x.id] } %></p>
</p>
<% end %>

app/views/topics/edit.html.erb
<h1><%= 'Edit Topic'[] %></h1>

<%= error_messages_for :topic %>
<% form_for :topic,
     :url  => forum_topic_path(@forum, @topic),
     :html => { :method => :put } do |f| -%>
<%= render :partial => "form", :object => f %>
<br />
<%= submit_tag 'Save Changes'[], :or => link_to('Cancel'[], forum_topic_path(@forum, @topic)) %>
<% end -%>

app/views/topics/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/posts/index.rhtml</p>

app/views/topics/new.html.erb
<div class="crumbs" xstyle="margin-top:1.1em;">
  <%= link_to 'Forums'[:forums_title], forums_path %> <span class="arrow">&rarr;</span>
  <%= link_to h(@forum.name), forum_path(@forum) %> <span class="arrow">&rarr;</span>
</div>


<h1 id="new_topic"><%= 'New Topic'[] %></h1>
<p class="subtitle"><%= 'by {user}'[:by_user, current_user.display_name] %></p>

<%= error_messages_for :post %>
<%= error_messages_for :topic %>
<% form_for :topic, :url  => forum_topics_path(@forum) do |f| -%>
<%= render :partial => "form", :object => f %>
<%= submit_tag 'Post Topic'[], :or => link_to('Cancel'[], forum_path(@forum)) %>
<% end -%>

<%= javascript_tag "$('topic_title').focus();" %>

app/views/topics/show.html.erb
<% @page_title = @topic.title %>
<% @monitoring = logged_in? && !Monitorship.count(:id, :conditions => ['user_id = ? and topic_id = ? and active = ?', current_user.id, @topic.id, true]).zero? %>

<% content_for :right do -%>

<h5><%= 'Voices'[:voices_title] %></h5>
<ul class="flat talking">
<% @topic.voices.each do | user | %>
  <li><%= link_to h(user.display_name), user_path(user) %></li>
<% end %>
</ul>


<% end # right content -%>

<% if logged_in? %>
<% form_tag forum_topic_monitorship_path(@forum, @topic), :style => 'margin-top:0em; float:right;' do -%>
<div>
  <input id="monitor_checkbox" type="checkbox" <%= "checked='checked'" if @monitoring %> 
    onclick="if (this.checked) {<%= remote_function :url => forum_topic_monitorship_path(@forum, @topic) %>} else {<%= remote_function :url => forum_topic_monitorship_path(@forum, @topic), :method => :delete %>}" />
  <label id="monitor_label" for="monitor_checkbox"><%= @monitoring ? 'Monitoring topic'[] : 'Monitor topic'[] %></label>
  <%= hidden_field_tag '_method', 'delete' if @monitoring %>
  <%= submit_tag :Set, :id => 'monitor_submit' %>
</div>
<% end -%>

<% end -%>


<div class="crumbs">
  <%= link_to "Forums"[:forums_title], forums_path %> <span class="arrow">&rarr;</span>
  <%= link_to h(@topic.forum.name), forum_path(@topic.forum) %> 
  <% 
  page=session[:forum_page] ? session[:forum_page][@topic.forum.id] : nil
  if page and page!=1 %>
  <small style="color:#ccc">
  (<%= link_to 'page {page}'[:page, page], forum_path(:id => @topic.forum, :page => page) %>)
  </small>
  <% end %>
  <span class="arrow">&rarr;</span>
</div>

<h1 id="topic-title" style="margin-top:0.5em;"<%= %( onmouseover="$('topic_mod').show();" onmouseout="$('topic_mod').hide();") if logged_in? %>>


  <%= h @topic.title %>
  <% if @topic.locked? %>
  <span>(<%= 'locked'[] %>)</span>
  <% end %>
  <% if logged_in? %>
    <span style="display:none;" id="topic_mod">
      <% if @topic.editable_by?(current_user) -%>
        <%= link_to('edit'[], edit_forum_topic_path(@forum, @topic), :class => "utility") %> |
        <%= link_to('delete'[], forum_topic_path(@forum, @topic), :class => "utility", :method => :delete, :confirm => 'Delete this topic forever?'[:delete_topic_conf]) %>
      <% end -%>
    </span>
  <% end %>
</h1>

<p class="subtitle">
  <%= feed_icon_tag @topic.title, forum_topic_path(@forum, @topic, :format => :rss) %>
  <%= '{count} post(s)'[(count=@topic.posts.size)==1 ? :post_count : :posts_count, number_with_delimiter(count)] %>, 
  <%= '{count} voice(s)'[(count=@topic.voices.size)==1 ? :voice_count : :voices_count, number_with_delimiter(count)] %>
</p>

<%= will_paginate @posts %>

<a name="<%= dom_id @posts.first %>" id="<%= dom_id @posts.first %>">&nbsp;</a>

<table border="0" cellspacing="0" cellpadding="0" class="posts wide">
<% for post in @posts do %>
<% unless post == @posts.first %>
<tr class="spacer">
  <td colspan="2">
    <a name="<%= dom_id post %>" id="<%= dom_id post %>">&nbsp;</a>
  </td>
</tr>
<% end %>
<tr class="post hentry" id="<%= dom_id post %>-row">
  <td class="author vcard">
    <div class="date">
      <a href="#<%= dom_id post %>" rel="bookmark">
      <abbr class="updated" title="<%= post.created_at.xmlschema %>">
      <%= time_ago_in_words(post.created_at) %>
      </abbr>
      </a>
    </div>

    <%= avatar_for post.user %>
    <span class="fn"><%= link_to truncate(h(post.user.display_name), 15), user_path(post.user), :class => (post.user == @posts.first.user ? "threadauthor" : nil) %></span>
    <% if post.user.admin? or post.forum.moderators.include?(post.user) %>
    <span class="admin">
      <% if post.user.admin? %>
      <%= 'Administator'[:administrator_title] %>
      <% elsif post.forum.moderators.include?(post.user) %>
      <%= 'Moderator'[:moderator_title] %>
      <% end %>
    </span>
    <% end %>
    <span class="posts"><%= '{count} post(s)'[(count=post.user.posts.size)==1 ? :post_count : :posts_count, number_with_delimiter(count)] %></span>


    <% if logged_in? && post.editable_by?(current_user) -%>
    <p>
      <span class="edit">
        <%= ajax_spinner_for "edit-post-#{post.id}", "spinner_bounce.gif" %>
        <%= link_to_remote('Edit post'[], 
              {:url => edit_post_path(:forum_id => @forum, :topic_id => @topic, :id => post), :method => :get,
               :before => "EditForm.init(#{post.id});", :condition => "!EditForm.isEditing(#{post.id})" }, 
              {:href => edit_post_path(:forum_id => @forum, :topic_id => @topic, :id => post, :page => params[:page]), :class => "utility"}) %>
      </span>
    </p>
    <% end -%>


  </td>
  <td class="body entry-content" id="post-body-<%= post.id %>">
<!--
    <%= link_to_function image_tag('clearbits/comment.gif', :class => 'icon reply'), "$('reply').toggle()" if logged_in? %>
-->
    <%= post.body_html %>
  </td>
</tr>

<% end %>
</table>
       
<%= will_paginate @posts %>

<% if logged_in? %>
<div id="edit"></div>
<% if @topic.locked? %>
<p>
    <%= image_tag "savage_beast/clearbits/lock.gif", :class => "icon grey", :title => "Topic locked"[:topic_locked_title] %> 
    <label>
    <%= 'This topic is locked'[:locked_topic] %>.</label>
</p>
<% else %>

<p><%= link_to_function 'Reply to topic'[], "ReplyForm.init()", :class => "utility" %></p>

<div id="reply" class="editbox">
<div class="container">
  <%= content_tag 'p', h(flash[:bad_reply]), :class => 'notice' if flash[:bad_reply] %>
  <% form_for :post, :url => posts_path(:forum_id => @forum, :topic_id => @topic, :page => @topic.last_page) do |f| -%>
  <table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td rowspan="2" width="70%">
        <%= f.text_area :body, :rows => 8 %>
      </td>
      <td valign="top">


        <h5><%= 'Formatting Help'[] %></h5>

        <ul class="help">
          <li><%= '*bold*'[:formatting_bold] %>
          &nbsp; &nbsp; &nbsp;
          <%= '_italics_'[:formatting_italics] %>
          &nbsp; &nbsp; &nbsp;<br />
          <%= 'bq. <span>(quotes)</span>'[:formatting_blockquote] %></li>
          <li>"IBM":http://www.ibm.com</li>
          <li><%= '* or # <span>(lists)</span>'[:formatting_list] %></li>
        </ul>

      </td>
    </tr>
    <tr>
      <td valign="bottom" style="padding-bottom:15px;">
       <%= submit_tag "Save Reply"[] %><span class="button_or">or <%= link_to_function 'cancel'[], "$('reply').hide()" %></span>
     </td>
   </tr>
  </table>
  <% end -%>
</div>
</div>
<%= javascript_tag "$('reply').hide();"%>
<% end %>
<% end %>

<div class="crumbs" style="margin-top:1.1em;">
  <%= link_to "Forums"[:forums_title], forums_path %> <span class="arrow">&rarr;</span>
  <%= link_to h(@topic.forum.name), forum_path(@topic.forum) %> <span class="arrow">&rarr;</span>
</div>