config/routes.rb
Rails.application.routes.draw do
  resources :forums do
    resources :topics do
      resources :posts
      resource :monitorship, :controller => :monitorships
    end
  end

  resources :posts, :as => "all_posts" do
    collection do
      get :index, :as => "all"
      get :search, :as => "search_all"
    end
  end

  %w(forum).each do |attr|
    resources :posts, :as => "#{attr}_posts", :path_prefix => "/#{attr.pluralize}/:#{attr}_id"
  end

  resources :topics
  resources :monitorship
end

app/views/layouts/_head.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%= "#{h @page_title} - " if @page_title %><%= 'Beast'[:beast_title] %></title>
  <%= stylesheet_link_tag 'savage_beast/display' %>
  <%= javascript_include_tag "application" %>
	<%# Assumption: If you're a rails project, you already have your own version of these, and don't need the SB version %>
	<%= javascript_include_tag "prototype", "effects" %>
<% unless @feed_icons.blank? -%>
  <% @feed_icons.each do |feed| -%>
  <%= auto_discovery_link_tag :rss, feed[:url], :title => "Subscribe to '#{feed[:title]}'" %>
  <% end -%>
<% end -%>
  <%= head_extras %>
  <link rel="search" type="application/opensearchdescription+xml" href="http://<%= request.host_with_port %>/open_search.xml" />
</head>
<body>

<div id="header">
	<ul id="nav">
		<li><%= link_to 'Forums'[:forums_title], forums_path, :rel => 'home' %></li>
		<li><%= link_to 'Users'[:users_title], users_path %></li>
		<li id="search">
		<% form_tag search_all_posts_url, :method => :get do -%>			
			<%= text_field_tag :q, params[:q], :size => 15, :id => :search_box %>
			<li><%= submit_tag 'Search'[:search_title] %></li>			
		<% end -%>
		</li>
		<li class="login"><%= beast_user_link %></li>		
  </ul>
  <h1><%= link_to 'Beast'[:beast_title], forums_path %></h1>
</div>
			

app/views/layouts/application.html.erb
<%= render :partial => "layouts/head" %>

<div id="container">

<div id="content">
  
<%= content_tag 'p', h(flash[:notice]), :class => 'notice' if flash[:notice] %>
<%= content_tag 'p', h(flash[:error]), :class => 'notice error' if flash[:error] %>
  
<%= yield %>
</div>

<div id="right">
  <%= yield :right %>
</div>

<br style="clear:both;" />

</div>

<div id="footer">
<p class="disclaim">
<strong>
  </strong>
</p>
<br style="clear:both;" />
</div>
</body>
</html>